trigger:
- master

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

pool:
  vmImage: 'ubuntu-latest'

steps:

# install Node.js and npm packages
- task: CacheBeta@0
  inputs:
    key: npm | $(Agent.OS) | package-lock.json
    path: $(npm_config_cache)
  displayName: cache npm packages

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'install Node.js'

- script: |
    npm ci -g @angular/cli@9.0.0-rc.12
    npm ci
  displayName: 'install npm packages'

# set-up and rund CouchDB in Docker container (used by unit tests)
- task: DownloadSecureFile@1
  displayName: 'download CouchDB local.ini file'
  name: couchdb_local_ini
  inputs:
    secureFile: 'couchdb_local.ini'    

- task: PowerShell@2
  displayName: 'copy CouchDB local.ini to target directory'
  inputs:
    targetType: 'inline'
    script: |
      New-Item -Type Directory -Force "${HOME}/couchdb/etc/local.d"
      Copy-Item -Force "$(couchdb_local_ini.secureFilePath)" "${HOME}/couchdb/etc/local.d/local.ini"    

- task: DockerInstaller@0
  displayName: install Docker
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable
    
- script: |
    docker run -p 5984:5984 --name couchdb -v ${HOME}/couchdb/etc/local.d:/opt/couchdb/etc/local.d -d couchdb
  displayName: 'run CouchDB in Docker container'

# perform unit-tets and publish test and code coverage results
- script: |
    npx ng test --watch=false --karmaConfig karma.conf.ci.js --code-coverage
  displayName: 'perform unit tests'    

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TESTS-*.xml'
  displayName: 'publish unit test results'

- task: PublishCodeCoverageResults@1
  displayName: 'publish code coverage report'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'
    failIfCoverageEmpty: true  

# build product and publish artifact
- script: |
    npx ng build --prod
  failOnStderr: true    
  displayName: 'build koia product'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'koiadist'
    targetPath: 'dist/koia'
  displayName: 'publish artifact'